version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_manager
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - postgres
